name: ephys_pipeline_env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - asttokens=3.0.0=py39haa95532_0
  - backcall=0.2.0=pyhd3eb1b0_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - colorama=0.4.6=py39haa95532_0
  - comm=0.2.1=py39haa95532_0
  - debugpy=1.8.16=py39h885b0b7_0
  - decorator=5.2.1=py39haa95532_0
  - exceptiongroup=1.3.0=py39haa95532_0
  - executing=2.2.1=py39haa95532_0
  - expat=2.7.3=h9214b88_0
  - importlib-metadata=8.5.0=py39haa95532_0
  - importlib_metadata=8.5.0=hd3eb1b0_0
  - ipykernel=6.30.1=py39haa95532_0
  - ipython=8.15.0=py39haa95532_0
  - jedi=0.19.2=py39haa95532_0
  - jupyter_client=8.6.3=py39haa95532_0
  - jupyter_core=5.8.1=py39haa95532_0
  - libffi=3.4.4=hd77b12b_1
  - libsodium=1.0.20=h83e8143_0
  - libzlib=1.3.1=h02ab6af_0
  - matplotlib-inline=0.1.7=py39haa95532_0
  - nest-asyncio=1.6.0=py39haa95532_0
  - openssl=3.0.18=h543e019_0
  - packaging=25.0=py39haa95532_1
  - parso=0.8.4=py39haa95532_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=25.3=pyhc872135_0
  - platformdirs=4.3.7=py39haa95532_0
  - prompt-toolkit=3.0.52=py39haa95532_1
  - pure_eval=0.2.3=py39haa95532_0
  - pygments=2.19.1=py39haa95532_0
  - python=3.9.25=h716150d_1
  - python-dateutil=2.9.0post0=py39haa95532_2
  - pywin32=311=py39h885b0b7_0
  - pyzmq=27.1.0=py39h7149c55_0
  - setuptools=80.9.0=py39haa95532_0
  - six=1.17.0=py39haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=py39haa95532_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.1=py39h827c3e9_0
  - traitlets=5.14.3=py39haa95532_0
  - typing-extensions=4.15.0=py39haa95532_0
  - typing_extensions=4.15.0=py39haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.13=py39haa95532_0
  - wheel=0.45.1=py39haa95532_0
  - xz=5.6.4=h4754444_1
  - zeromq=4.3.5=h6c54ac7_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - contourpy==1.3.0
      - cycler==0.12.1
      - faiss-cpu==1.13.0
      - filelock==3.19.1
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - kilosort==0.1.dev1503+g57ebd93f4
      - kiwisolver==1.4.7
      - llvmlite==0.43.0
      - markupsafe==3.0.3
      - matlabengineforpython==9.14
      - matplotlib==3.9.4
      - mpmath==1.3.0
      - networkx==3.2.1
      - numba==0.60.0
      - numpy==2.0.2
      - pandas==2.3.3
      - pillow==11.3.0
      - psutil==7.1.3
      - pyparsing==3.2.5
      - pytz==2025.2
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - torch==2.7.1+cu118
      - tqdm==4.67.1
      - tzdata==2025.2
      - zipp==3.23.0
prefix: C:\ProgramData\miniconda3\envs\ephys_pipeline_env
